services:
  front:
    image: sns-front:latest
    ports:
      - "3000:3000"
    env_file:
      - front/.env.dev

  back:
    image: sns-back:latest
    ports:
      - "8080:8080"
    env_file:
      - backend/.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    env_file:
      - backend/.env.dev
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
