services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    image: sns-front:1.0
    container_name: sns-front-dev
    volumes:
      - ./front/app:/app/app
      - ./front/jsconfig.json:/app/jsconfig.json
      - /app/node_modules
    env_file:
      - ./front/.env.dev
    ports:
      - "3000:3000"

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: sns-back:1.0
    container_name: sns-backend-dev
    env_file:
      - ./backend/.env.dev
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sns-mysql-dev
    env_file:
      - ./backend/.env.dev
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
