services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sns-front:1.0
    container_name: sns-front-dev
    volumes:
      - ./app:/app/app
      - ./jsconfig.json:/app/jsconfig.json
      - /app/node_modules
    env_file:
      - .env.dev
    ports:
      - "3000:3000"